### ISSUE TITLE
Resources URL update

### ISSUE THREAD

**Issue by Eugenijus** [kentcdodds/what-test-slides#1]
I suggest these updates

**slides/01.md**
FROM `- Slides https://github.com/kentcdodds/practically-testing-slides`
TO `- Slides https://github.com/kentcdodds/what-test-slides`

**slides/11.md**
FROM `[AssertJS 2018](https://2018.assertjs.com):`
TO `[AssertJS 2018](http://web.archive.org/web/20180411223419/https://www.assertjs.com/):`

Address http://assertjs.com/ is returning 404 and website is no longer available. Instead as workaround, it still can opened using web archive.

**Comment by kentcdodds** [comment]
Thanks! Fixed :)
